"""
This type stub file was generated by pyright.
"""

from typing import Optional
from .controller import Controller
from .define import *
from .resource import Resource
from .tasker import Tasker

class AgentClient:
    """Agent 客户端 / Agent client

    用于连接到 AgentServer，将自定义识别器和动作的执行委托给独立进程。
    这允许将 MaaFW 本体与 Custom 逻辑分离至独立进程运行。
    Used to connect to AgentServer, delegating custom recognition and action execution to a separate
    process.
    This allows separating MaaFW core from Custom logic into independent processes.
    """
    _handle: MaaAgentClientHandle
    def __init__(self, identifier: Optional[str] = ..., *, _handle: Optional[MaaAgentClientHandle] = ...) -> None:
        """创建 Agent 客户端 / Create Agent client

        默认使用 IPC 模式；如果 identifier 为纯数字字符串，则会将其视为 TCP 端口号并监听 127.0.0.1。
        在不支持 AF_UNIX 的旧版 Windows（Build 17063 之前）上也会自动回退到 TCP 模式。
        Uses IPC mode by default; if identifier is a numeric string, it is treated as a TCP port
        and listens on 127.0.0.1. On older Windows versions that don't support AF_UNIX
        (before Build 17063), it will also automatically fall back to TCP mode.

        Args:
            identifier: 可选的连接标识符；纯数字字符串会被视为 TCP 端口号 /
                Optional connection identifier; numeric strings are treated as TCP ports
            _handle: 内部使用，直接传入已创建的句柄 / Internal use, directly pass in an already created handle

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    
    @classmethod
    def create_tcp(cls, port: int = ...) -> AgentClient:
        """创建使用 TCP 连接的 Agent 客户端 / Create Agent client with TCP connection

        客户端会监听 127.0.0.1 上的指定端口。如果传入 0 则自动选择可用端口。
        AgentServer 端使用 identifier 属性获取的端口号作为 identifier 即可通过 TCP 连接。
        The client listens on 127.0.0.1 at the specified port. If 0 is passed, an available port is
        automatically selected.
        AgentServer can use the port number from the identifier property to connect via TCP.

        Args:
            port: TCP 端口号 (0-65535)，0 表示自动选择 / TCP port number (0-65535), 0 means auto-select

        Returns:
            AgentClient: TCP 模式的客户端实例 / Client instance in TCP mode

        Raises:
            RuntimeError: 如果创建失败
            ValueError: 如果端口号无效
        """
        ...
    
    def __del__(self): # -> None:
        ...
    
    @property
    def identifier(self) -> Optional[str]:
        """获取连接标识符 / Get connection identifier

        Returns:
            Optional[str]: 连接标识符，如果未设置则返回 None / Connection identifier, or None if not set
        """
        ...
    
    def bind(self, resource: Resource) -> bool:
        """绑定资源 / Bind resource

        将 AgentServer 中注册的自定义识别器和动作绑定到资源上。
        Bind custom recognitions and actions registered in AgentServer to the resource.

        Args:
            resource: 资源对象 / Resource object

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def register_sink(self, resource: Resource, controller: Controller, tasker: Tasker) -> bool:
        """注册事件监听器 / Register event sinks

        将资源、控制器、任务器的事件转发给 AgentServer。
        Forward resource, controller, and tasker events to AgentServer.

        Args:
            resource: 资源对象 / Resource object
            controller: 控制器对象 / Controller object
            tasker: 任务器对象 / Tasker object

        Returns:
            bool: 是否全部注册成功 / Whether all registrations succeeded
        """
        ...
    
    def connect(self) -> bool:
        """连接到 AgentServer / Connect to AgentServer

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def disconnect(self) -> bool:
        """断开与 AgentServer 的连接 / Disconnect from AgentServer

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def connected(self) -> bool:
        """判断是否已连接 / Check if connected

        Returns:
            bool: 是否已连接 / Whether connected
        """
        ...
    
    @property
    def alive(self) -> bool:
        """判断连接是否存活 / Check if connection is alive

        Returns:
            bool: 连接是否存活 / Whether connection is alive
        """
        ...
    
    def set_timeout(self, milliseconds: int) -> bool:
        """设置超时时间 / Set timeout

        Args:
            milliseconds: 超时时间（毫秒） / Timeout in milliseconds

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def custom_recognition_list(self) -> list[str]:
        """获取已注册的自定义识别器列表 / Get registered custom recognizer list

        Returns:
            list[str]: 自定义识别器名列表 / List of custom recognizer names

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def custom_action_list(self) -> list[str]:
        """获取已注册的自定义操作列表 / Get registered custom action list

        Returns:
            list[str]: 自定义操作名列表 / List of custom action names

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    _api_properties_initialized: bool = ...


