"""
This type stub file was generated by pyright.
"""

import numpy
from typing import Optional, Union
from .define import *

class StringBuffer:
    """字符串缓冲区 / String buffer

    用于在 Python 和 C API 之间传递字符串数据。
    Used to pass string data between Python and C API.
    """
    _handle: MaaStringBufferHandle
    _own: bool
    def __init__(self, handle: Optional[MaaStringBufferHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get(self) -> str:
        """获取缓冲区内容 / Get buffer content

        Returns:
            str: 字符串内容 / String content
        """
        ...
    
    def set(self, value: Union[str, bytes]) -> bool:
        """设置缓冲区内容 / Set buffer content

        Args:
            value: 字符串或字节数据 / String or bytes data

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def empty(self) -> bool:
        """判断缓冲区是否为空 / Check if buffer is empty

        Returns:
            bool: 是否为空 / Whether empty
        """
        ...
    
    def clear(self) -> bool:
        """清空缓冲区 / Clear buffer

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _api_properties_initialized: bool = ...


class StringListBuffer:
    """字符串列表缓冲区 / String list buffer

    用于在 Python 和 C API 之间传递字符串列表数据。
    Used to pass string list data between Python and C API.
    """
    _handle: MaaStringListBufferHandle
    _own: bool
    def __init__(self, handle: Optional[MaaStringListBufferHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get(self) -> list[str]:
        """获取字符串列表 / Get string list

        Returns:
            List[str]: 字符串列表 / String list
        """
        ...
    
    def set(self, value: list[str]) -> bool:
        """设置字符串列表 / Set string list

        Args:
            value: 字符串列表 / String list

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def append(self, value: str) -> bool:
        """追加字符串 / Append string

        Args:
            value: 要追加的字符串 / String to append

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def remove(self, index: int) -> bool:
        """移除指定索引的字符串 / Remove string at index

        Args:
            index: 要移除的索引 / Index to remove

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def clear(self) -> bool:
        """清空列表 / Clear list

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _api_properties_initialized: bool = ...


class ImageBuffer:
    """图像缓冲区 / Image buffer

    用于在 Python 和 C API 之间传递图像数据。图像格式为 BGR，与 OpenCV 兼容。
    Used to pass image data between Python and C API. Image format is BGR, compatible with OpenCV.
    """
    _handle: MaaImageBufferHandle
    _own: bool
    def __init__(self, c_handle: Optional[MaaImageBufferHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get(self) -> numpy.ndarray:
        """获取图像数据 / Get image data

        Returns:
            numpy.ndarray: BGR 格式图像，形状为 (height, width, channels)
            BGR format image with shape (height, width, channels)
        """
        ...
    
    def set(self, value: numpy.ndarray) -> bool:
        """设置图像数据 / Set image data

        Args:
            value: BGR 格式图像，形状为 (height, width, channels)
            BGR format image with shape (height, width, channels)

        Returns:
            bool: 是否成功 / Whether successful

        Raises:
            TypeError: 如果 value 不是 numpy.ndarray
        """
        ...
    
    def resize(self, width: int = ..., height: int = ...) -> bool:
        """调整图像尺寸 / Resize image

        Args:
            width: 目标宽度，0 表示按高度等比缩放 / Target width, 0 to scale by height
            height: 目标高度，0 表示按宽度等比缩放 / Target height, 0 to scale by width

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def empty(self) -> bool:
        """判断缓冲区是否为空 / Check if buffer is empty

        Returns:
            bool: 是否为空 / Whether empty
        """
        ...
    
    def clear(self) -> bool:
        """清空缓冲区 / Clear buffer

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _api_properties_initialized: bool = ...


class ImageListBuffer:
    """图像列表缓冲区 / Image list buffer

    用于在 Python 和 C API 之间传递图像列表数据。
    Used to pass image list data between Python and C API.
    """
    _handle: MaaImageListBufferHandle
    _own: bool
    def __init__(self, c_handle: Optional[MaaImageListBufferHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get(self) -> list[numpy.ndarray]:
        """获取图像列表 / Get image list

        Returns:
            List[numpy.ndarray]: 图像列表 / Image list
        """
        ...
    
    def set(self, value: list[numpy.ndarray]) -> bool:
        """设置图像列表 / Set image list

        Args:
            value: 图像列表 / Image list

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def append(self, value: numpy.ndarray) -> bool:
        """追加图像 / Append image

        Args:
            value: 要追加的图像 / Image to append

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def remove(self, index: int) -> bool:
        """移除指定索引的图像 / Remove image at index

        Args:
            index: 要移除的索引 / Index to remove

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def clear(self) -> bool:
        """清空列表 / Clear list

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _api_properties_initialized: bool = ...


class RectBuffer:
    """矩形缓冲区 / Rectangle buffer

    用于在 Python 和 C API 之间传递矩形数据（x, y, width, height）。
    Used to pass rectangle data (x, y, width, height) between Python and C API.
    """
    _handle: MaaRectHandle
    _own: bool
    def __init__(self, c_handle: Optional[MaaRectHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get(self) -> Rect:
        """获取矩形数据 / Get rectangle data

        Returns:
            Rect: 矩形对象 (x, y, width, height) / Rectangle object (x, y, width, height)
        """
        ...
    
    def set(self, value: RectType) -> bool:
        """设置矩形数据 / Set rectangle data

        Args:
            value: 矩形数据，可以是 Rect、tuple、list 或 numpy.ndarray
            Rectangle data, can be Rect, tuple, list, or numpy.ndarray

        Returns:
            bool: 是否成功 / Whether successful

        Raises:
            ValueError: 如果数据格式不正确
            TypeError: 如果类型不支持
        """
        ...
    
    _api_properties_initialized: bool = ...


