"""
This type stub file was generated by pyright.
"""

import numpy
from dataclasses import dataclass
from typing import Any, Optional
from .define import *
from .event_sink import EventSink, NotificationType
from .job import TaskJob
from .pipeline import JActionParam, JActionType, JNodeAttr, JPipelineData, JRecognitionParam, JRecognitionType, JWaitFreezes
from .tasker import Tasker

class Context:
    _handle: MaaContextHandle
    _tasker: Tasker
    def __init__(self, handle: MaaContextHandle) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def run_task(self, entry: str, pipeline_override: Optional[dict[str, Any]] = ...) -> Optional[TaskDetail]:
        """同步执行任务 / Synchronously execute task

        Args:
            entry: 任务入口 / Task entry
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            Optional[TaskDetail]: 任务详情，执行失败则返回 None / Task detail, or None if execution failed
        """
        ...
    
    def run_recognition(self, entry: str, image: numpy.ndarray, pipeline_override: Optional[dict[str, Any]] = ...) -> Optional[RecognitionDetail]:
        """同步执行识别逻辑 / Synchronously execute recognition logic

        不会执行后续操作, 不会执行后续 next
        Will not execute subsequent operations or next steps

        Args:
            entry: 任务名 / Task name
            image: 前序截图 / Previous screenshot
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            Optional[RecognitionDetail]: 识别结果。无论是否命中，只要尝试进行了识别，就会返回；
            请通过 RecognitionDetail.hit 判断是否命中。只在未能启动识别流程时（如 entry 不存在、node disabled、image
            为空等），才可能返回
            None。
            Recognition detail. It always returns as long as recognition was attempted;
            use RecognitionDetail.hit to determine hit. Only return None if the recognition process
            fails to start
            (e.g., entry does not exist, node is disabled, image is empty).
        """
        ...
    
    def run_action(self, entry: str, box: RectType = ..., reco_detail: str = ..., pipeline_override: Optional[dict[str, Any]] = ...) -> Optional[ActionDetail]:
        """同步执行操作逻辑 / Synchronously execute action logic

        不会执行后续 next
        Will not execute subsequent next steps

        Args:
            entry: 任务名 / Task name
            box: 前序识别位置 / Previous recognition position
            reco_detail: 前序识别详情 / Previous recognition details
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            Optional[ActionDetail]: 操作结果。无论动作是否成功，只要尝试执行了动作，就会返回；
            请通过 ActionDetail.success 判断是否执行成功。只在未能启动动作流程时（如 entry 不存在、node disabled
            等），才可能返回 None。
            Action detail. It always returns as long as the action was attempted;
            use ActionDetail.success to determine success. Only return None if the action flow fails
            to start
            (e.g., entry does not exist, node is disabled, etc.).
        """
        ...
    
    def run_recognition_direct(self, reco_type: JRecognitionType, reco_param: JRecognitionParam, image: numpy.ndarray) -> Optional[RecognitionDetail]:
        """同步执行识别 / Synchronously execute recognition

        直接使用识别类型和参数执行，无需通过 pipeline entry。
        Execute directly with recognition type and parameters, without requiring a pipeline entry.

        Args:
            reco_type: 识别类型 / Recognition type
            reco_param: 识别参数 / Recognition parameters
            image: 前序截图 / Previous screenshot

        Returns:
            Optional[RecognitionDetail]: 识别结果。无论是否命中，只要尝试进行了识别，就会返回；
            请通过 RecognitionDetail.hit 判断是否命中。只在未能启动识别流程时才可能返回 None。
            Recognition detail. It always returns as long as recognition was attempted;
            use RecognitionDetail.hit to determine hit. Only return None if the recognition process
            fails to start.
        """
        ...
    
    def run_action_direct(self, action_type: JActionType, action_param: JActionParam, box: RectType = ..., reco_detail: str = ...) -> Optional[ActionDetail]:
        """同步执行操作 / Synchronously execute action

        直接使用操作类型和参数执行，无需通过 pipeline entry。
        Execute directly with action type and parameters, without requiring a pipeline entry.

        Args:
            action_type: 操作类型 / Action type
            action_param: 操作参数 / Action parameters
            box: 前序识别位置 / Previous recognition position
            reco_detail: 前序识别详情 / Previous recognition details

        Returns:
            Optional[ActionDetail]: 操作结果。无论动作是否成功，只要尝试执行了动作，就会返回；
            请通过 ActionDetail.success 判断是否执行成功。只在未能启动动作流程时才可能返回 None。
            Action detail. It always returns as long as the action was attempted;
            use ActionDetail.success to determine success. Only return None if the action flow fails
            to start.
        """
        ...
    
    def override_pipeline(self, pipeline_override: dict[str, Any]) -> bool:
        """覆盖 pipeline / Override pipeline_override

        Args:
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def override_next(self, name: str, next_list: list[str]) -> bool:
        """覆盖任务的 next 列表 / Override the next list of task

        如果节点不存在，此方法会失败
        This method will fail if the node does not exist

        Args:
            name: 任务名 / Task name
            next_list: next 列表 / Next list

        Returns:
            bool: 成功返回 True，如果节点不存在则返回 False / Returns True on success, False if node does not exist
        """
        ...
    
    def override_image(self, image_name: str, image: numpy.ndarray) -> bool:
        """覆盖图片 / Override the image corresponding to image_name

        Args:
            image_name: 图片名 / Image name
            image: 图片数据 / Image data

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def get_node_data(self, name: str) -> Optional[dict[str, Any]]:
        """获取任务当前的定义 / Get the current definition of task

        Args:
            name: 任务名 / Task name

        Returns:
            Optional[Dict]: 任务定义字典，如果不存在则返回 None / Task definition dict, or None if not exists
        """
        ...
    
    def get_node_object(self, name: str) -> Optional[JPipelineData]:
        """获取任务当前的定义（解析为对象） / Get the current definition of task (parsed as object)

        Args:
            name: 任务名 / Task name

        Returns:
            Optional[JPipelineData]: 任务定义对象，如果不存在则返回 None
            Task definition object, or None if not exists
        """
        ...
    
    @property
    def tasker(self) -> Tasker:
        """获取实例 / Get instance

        Returns:
            Tasker: 实例对象 / Instance object
        """
        ...
    
    def get_task_job(self) -> TaskJob:
        """获取对应任务号的任务作业 / Get task job for corresponding task id

        Returns:
            TaskJob: 任务作业对象 / Task job object

        Raises:
            ValueError: 如果任务 id 为 None
        """
        ...
    
    def clone(self) -> Context:
        """复制上下文 / Clone context

        Returns:
            Context: 复制的上下文对象 / Cloned context object

        Raises:
            ValueError: 如果克隆失败
        """
        ...
    
    def set_anchor(self, anchor_name: str, node_name: str) -> bool:
        """设置锚点 / Set anchor

        Args:
            anchor_name: 锚点名称 / Anchor name
            node_name: 节点名称 / Node name

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def get_anchor(self, anchor_name: str) -> Optional[str]:
        """获取锚点对应的节点名 / Get node name for anchor

        Args:
            anchor_name: 锚点名称 / Anchor name

        Returns:
            Optional[str]: 节点名称，如果不存在则返回 None / Node name, or None if not exists
        """
        ...
    
    def get_hit_count(self, node_name: str) -> int:
        """获取节点命中计数 / Get hit count for node

        Args:
            node_name: 节点名称 / Node name

        Returns:
            int: 命中计数 / Hit count
        """
        ...
    
    def clear_hit_count(self, node_name: str) -> bool:
        """清除节点命中计数 / Clear hit count for node

        Args:
            node_name: 节点名称 / Node name

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def wait_freezes(self, time: int = ..., box: Optional[tuple[int, int, int, int]] = ..., wait_freezes_param: Optional[JWaitFreezes] = ...) -> bool:
        """等待画面静止 / Wait for screen to stabilize (freeze)

        Args:
            time: 等待时间（毫秒） / Wait time in milliseconds
            box: 识别命中的区域 (x, y, w, h)，用于 target 为 Self 时计算 ROI
            Recognition hit box, used when target is Self to calculate ROI
            wait_freezes_param: 等待参数，使用 JWaitFreezes。支持 time, target, target_offset, threshold,
            method, rate_limit, timeout

                              Wait parameters, use JWaitFreezes. Supports time, target,
                              target_offset, threshold, method, rate_limit, timeout

        Returns:
            bool: 是否成功 / Whether successful

        Note:
            - time 和 wait_freezes_param.time 互斥，不能同时为非零或同时为零
            time and wait_freezes_param.time are mutually exclusive
        """
        ...
    
    _api_properties_initialized: bool = ...


class ContextEventSink(EventSink):
    @dataclass
    class NodeWaitFreezesDetail:
        task_id: int
        wf_id: int
        name: str
        phase: str
        roi: tuple[int, int, int, int]
        param: dict[str, Any]
        reco_ids: list[int]
        elapsed: Optional[int]
        focus: Any
        ...
    
    
    def on_node_wait_freezes(self, context: Context, noti_type: NotificationType, detail: NodeWaitFreezesDetail): # -> None:
        ...
    
    @dataclass
    class NodeNextListDetail:
        task_id: int
        name: str
        next_list: list[JNodeAttr]
        focus: Any
        ...
    
    
    def on_node_next_list(self, context: Context, noti_type: NotificationType, detail: NodeNextListDetail): # -> None:
        ...
    
    @dataclass
    class NodeRecognitionDetail:
        task_id: int
        reco_id: int
        name: str
        focus: Any
        anchor: Optional[str] = ...
    
    
    def on_node_recognition(self, context: Context, noti_type: NotificationType, detail: NodeRecognitionDetail): # -> None:
        ...
    
    @dataclass
    class NodeActionDetail:
        task_id: int
        action_id: int
        name: str
        focus: Any
        ...
    
    
    def on_node_action(self, context: Context, noti_type: NotificationType, detail: NodeActionDetail): # -> None:
        ...
    
    @dataclass
    class NodePipelineNodeDetail:
        task_id: int
        node_id: int
        name: str
        focus: Any
        ...
    
    
    def on_node_pipeline_node(self, context: Context, noti_type: NotificationType, detail: NodePipelineNodeDetail): # -> None:
        ...
    
    @dataclass
    class NodeRecognitionNodeDetail:
        task_id: int
        node_id: int
        name: str
        focus: Any
        ...
    
    
    def on_node_recognition_node(self, context: Context, noti_type: NotificationType, detail: NodeRecognitionNodeDetail): # -> None:
        ...
    
    @dataclass
    class NodeActionNodeDetail:
        task_id: int
        node_id: int
        name: str
        focus: Any
        ...
    
    
    def on_node_action_node(self, context: Context, noti_type: NotificationType, detail: NodeActionNodeDetail): # -> None:
        ...
    
    def on_raw_notification(self, context: Context, msg: str, details: dict[str, Any]) -> None:
        ...
    


