"""
This type stub file was generated by pyright.
"""

import ctypes
import numpy
from abc import abstractmethod
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union
from .define import *
from .event_sink import EventSink, NotificationType
from .job import Job, JobWithResult

__all__ = ["AdbController", "DbgController", "ReplayController", "RecordController", "PlayCoverController", "Win32Controller", "GamepadController", "WlRootsController", "AndroidNativeController", "CustomController"]
class Controller:
    _handle: MaaControllerHandle
    _own: bool
    def __init__(self, handle: Optional[MaaControllerHandle] = ...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def post_connection(self) -> Job:
        """异步连接设备 / Asynchronously connect device

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def post_click(self, x: int, y: int, contact: int = ..., pressure: int = ...) -> Job:
        """异步点击 / Asynchronously click

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        Args:
            x: x 坐标 / x coordinate
            y: y 坐标 / y coordinate
            contact: 触点编号 (Adb 控制器: 手指编号; Win32 控制器: 鼠标按键 0:左键, 1:右键, 2:中键)
            Contact number (Adb controller: finger number; Win32 controller: mouse button 0:left,
            1:right, 2:middle)
            pressure: 触点力度 / Contact pressure

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def post_swipe(self, x1: int, y1: int, x2: int, y2: int, duration: int, contact: int = ..., pressure: int = ...) -> Job:
        """滑动 / Swipe

        Args:
            x1: 起点 x 坐标 / Start x coordinate
            y1: 起点 y 坐标 / Start y coordinate
            x2: 终点 x 坐标 / End x coordinate
            y2: 终点 y 坐标 / End y coordinate
            duration: 滑动时长(毫秒) / Swipe duration in milliseconds
            contact: 触点编号 (Adb 控制器: 手指编号; Win32 控制器: 鼠标按键 0:左键, 1:右键, 2:中键)
            Contact number (Adb controller: finger number; Win32 controller: mouse button 0:left,
            1:right, 2:middle)
            pressure: 触点力度 / Contact pressure

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_press_key(self, key: int) -> Job:
        """
        Deprecated: Use post_click_key instead.
        """
        ...
    
    def post_click_key(self, key: int) -> Job:
        """单击按键 / Click key

        Args:
            key: 虚拟键码 / Virtual key code

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_key_down(self, key: int) -> Job:
        """按下键 / Key down

        Args:
            key: 虚拟键码 / Virtual key code

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_key_up(self, key: int) -> Job:
        """抬起键 / Key up

        Args:
            key: 虚拟键码 / Virtual key code

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_input_text(self, text: str) -> Job:
        """输入文本 / Input text

        Args:
            text: 要输入的文本 / Text to input

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_start_app(self, intent: str) -> Job:
        """启动应用 / Start app

        Args:
            intent: 目标应用 (Adb 控制器: package name 或 activity)
            Target app (Adb controller: package name or activity)

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_stop_app(self, intent: str) -> Job:
        """关闭应用 / Stop app

        Args:
            intent: 目标应用 (Adb 控制器: package name) / Target app (Adb controller: package name)

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_touch_down(self, x: int, y: int, contact: int = ..., pressure: int = ...) -> Job:
        """按下 / Touch down

        Args:
            x: x 坐标 / x coordinate
            y: y 坐标 / y coordinate
            contact: 触点编号 (Adb 控制器: 手指编号; Win32 控制器: 鼠标按键 0:左键, 1:右键, 2:中键)
            Contact number (Adb controller: finger number; Win32 controller: mouse button 0:left,
            1:right, 2:middle)
            pressure: 触点力度 / Contact pressure

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_touch_move(self, x: int, y: int, contact: int = ..., pressure: int = ...) -> Job:
        """移动 / Move

        Args:
            x: x 坐标 / x coordinate
            y: y 坐标 / y coordinate
            contact: 触点编号 (Adb 控制器: 手指编号; Win32 控制器: 鼠标按键 0:左键, 1:右键, 2:中键)
            Contact number (Adb controller: finger number; Win32 controller: mouse button 0:left,
            1:right, 2:middle)
            pressure: 触点力度 / Contact pressure

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_touch_up(self, contact: int = ...) -> Job:
        """抬起 / Touch up

        Args:
            contact: 触点编号 (Adb 控制器: 手指编号; Win32 控制器: 鼠标按键 0:左键, 1:右键, 2:中键)
            Contact number (Adb controller: finger number; Win32 controller: mouse button 0:left,
            1:right, 2:middle)

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def post_relative_move(self, dx: int, dy: int) -> Job:
        """异步执行一次相对位移 (当前仅 Win32 controller 支持)
        Asynchronously execute a relative movement (Currently only supported by Win32 controller)

        Args:
            dx: x 方向移动偏移 / x axis offset
            dy: y 方向移动偏移 / y axis offset

        Returns:
            Job: 作业对象 / Job object
        """
        ...
    
    def set_mouse_lock_follow(self, enabled: bool) -> bool:
        """设置鼠标锁定跟随模式 (Win32 controller) / Set mouse lock follow mode (Win32 controller)

        Args:
            enabled: 是否开启 / Whether to enable

        Returns:
            bool: 是否设置成功 / Whether the setting was successful

        Note:
            适用于 TPS/FPS 等在后台锁定鼠标的游戏 / For TPS/FPS games that lock the mouse in the background
        """
        ...
    
    def set_background_managed_keys(self, keys: Sequence[int]) -> bool:
        ...
    
    def post_scroll(self, dx: int, dy: int) -> Job:
        """滚动 / Scroll

        Args:
            dx: 水平滚动距离，正值向右滚动，负值向左滚动
            Horizontal scroll distance, positive for right, negative for left
            dy: 垂直滚动距离，正值向上滚动，负值向下滚动 / Vertical scroll distance, positive for up, negative for down

        Returns:
            Job: 作业对象 / Job object

        Note:
            Win32 控制器和实现了 scroll 的自定义控制器支持滚动操作
            Win32 controllers and custom controllers that implement scroll support this operation
            建议使用 120 的整数倍（WHEEL_DELTA）以获得最佳兼容性 / Using multiples of 120 (WHEEL_DELTA) is recommended
        """
        ...
    
    def post_screencap(self) -> JobWithResult[numpy.ndarray]:
        """截图 / Screenshot

        Returns:
            JobWithResult: 作业对象，可通过 result 获取截图 / Job object, can get screenshot via result
        """
        ...
    
    @property
    def cached_image(self) -> numpy.ndarray:
        """获取最新一次截图 / Get the latest screenshot

        Returns:
            numpy.ndarray: 截图图像 / Screenshot image

        Raises:
            RuntimeError: 如果获取失败

        Note:
            返回的图像是经过缩放的，尺寸根据截图目标尺寸设置（长边/短边）而定，可能与设备原始分辨率不同。
            使用 resolution 属性可获取设备的原始（未缩放）分辨率。

            The returned image is scaled according to the screenshot target size settings (long side
            short side).
            The image dimensions may differ from the raw device resolution.
            Use the resolution property to get the raw (unscaled) device resolution.
        """
        ...
    
    def post_shell(self, cmd: str, timeout: int = ...) -> JobWithResult[str]:
        """执行 shell 命令 (仅 ADB 控制器) / Execute shell command (ADB only)

        Args:
            cmd: shell 命令 / shell command
            timeout: 超时时间（毫秒），默认 20000，设置为 -1 表示无限等待
            Timeout in milliseconds, default 20000, set to -1 for infinite wait

        Returns:
            JobWithResult: 作业对象，可通过 result 获取命令输出 / Job object, can get output via result
        """
        ...
    
    def post_inactive(self) -> Job:
        """设置控制器为不活跃状态 / Set controller to inactive state

        对于 Win32 控制器，这会恢复窗口位置（取消置顶）并解除输入阻断。
        对于其他控制器，这是一个空操作，总是成功。

        For Win32 controllers, this restores window position (removes topmost) and unblocks user
        input.
        For other controllers, this is a no-op that always succeeds.

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    @property
    def shell_output(self) -> str:
        """获取最近一次 shell 命令输出 / Get the latest shell command output

        Returns:
            str: shell 命令输出 / shell command output

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def connected(self) -> bool:
        """判断是否已连接 / Check if connected

        Returns:
            bool: 是否已连接 / Whether connected
        """
        ...
    
    @property
    def uuid(self) -> str:
        """获取设备 uuid / Get device uuid

        Returns:
            str: 设备 uuid / Device uuid

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def info(self) -> dict[str, Any]:
        """获取控制器信息 / Get controller information

        Returns:
            Dict[str, Any]: 控制器信息，包含类型、构造参数等
            Controller information including type, constructor parameters, etc.

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def resolution(self) -> tuple[int, int]:
        """获取设备原始（未缩放）分辨率 / Get the raw (unscaled) device resolution

        Returns:
            Tuple[int, int]: (宽度, 高度)，获取失败时返回 (0, 0) / (width, height), returns (0, 0) on failure

        Note:
            返回的是设备屏幕的实际分辨率，未经任何缩放处理。
            而通过 cached_image 获取的截图是经过缩放的，其尺寸可能与此原始分辨率不同。
            需要在首次截图后才能获取到有效值，否则返回 (0, 0)。

            This returns the actual device screen resolution before any scaling.
            The screenshot obtained via cached_image is scaled according to the screenshot target
            size settings,
            so its dimensions may differ from this raw resolution.
            Valid values are only available after the first screenshot is taken, otherwise returns
            (0, 0).
        """
        ...
    
    def set_screenshot_target_long_side(self, long_side: int) -> bool:
        """设置截图缩放长边到指定长度 / Set screenshot scaling long side to specified length

        Args:
            long_side: 长边长度 / Long side length

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def set_screenshot_target_short_side(self, short_side: int) -> bool:
        """设置截图缩放短边到指定长度 / Set screenshot scaling short side to specified length

        Args:
            short_side: 短边长度 / Short side length

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def set_screenshot_use_raw_size(self, enable: bool) -> bool:
        """设置截图不缩放 / Set screenshot use raw size without scaling

        注意：此选项可能导致在不同分辨率的设备上坐标不正确
        Note: This option may cause incorrect coordinates on devices with different resolutions

        Args:
            enable: 是否启用 / Whether to enable

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def set_screenshot_resize_method(self, method: int) -> bool:
        """设置截图缩放插值方法 / Set screenshot resize interpolation method

        值对应 cv::InterpolationFlags / Value corresponds to cv::InterpolationFlags:
          INTER_NEAREST=0, INTER_LINEAR=1, INTER_CUBIC=2, INTER_AREA=3, INTER_LANCZOS4=4

        Args:
            method: 插值方法 / Interpolation method (default: 3, INTER_AREA)

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _sink_holder: dict[int, ControllerEventSink] = ...
    def add_sink(self, sink: ControllerEventSink) -> Optional[int]:
        """添加控制器事件监听器 / Add controller event listener

        Args:
            sink: 事件监听器 / Event sink

        Returns:
            Optional[int]: 监听器 id，失败返回 None / Listener id, or None if failed
        """
        ...
    
    def remove_sink(self, sink_id: int) -> None:
        """移除控制器事件监听器 / Remove controller event listener

        Args:
            sink_id: 监听器 id / Listener id
        """
        ...
    
    def clear_sinks(self) -> None:
        """清除所有控制器事件监听器 / Clear all controller event listeners"""
        ...
    
    _api_properties_initialized: bool = ...


class AdbController(Controller):
    """Adb 控制器 / Adb controller

    截图方式和输入方式会在启动时进行测速, 选择最快的方案
    Screenshot and input methods will be speed tested at startup, selecting the fastest option
    """
    AGENT_BINARY_PATH = ...
    def __init__(self, adb_path: Union[str, Path], address: str, screencap_methods: int = ..., input_methods: int = ..., config: Optional[dict[str, Any]] = ..., agent_path: Union[str, Path] = ...) -> None:
        """创建 Adb 控制器 / Create Adb controller

        Args:
            adb_path: adb 路径 / adb path
            address: 连接地址 / connection address
            screencap_methods: 所有可使用的截图方式 / all available screenshot methods
            input_methods: 所有可使用的输入方式 / all available input methods
            config: 额外配置 / extra config
            agent_path: MaaAgentBinary 路径 / MaaAgentBinary path

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class Win32Controller(Controller):
    """Win32 控制器 / Win32 controller"""
    def __init__(self, hWnd: Union[ctypes.c_void_p, int, None], screencap_method: int = ..., mouse_method: int = ..., keyboard_method: int = ...) -> None:
        """创建 Win32 控制器 / Create Win32 controller

        Args:
            hWnd: 窗口句柄 / window handle
            screencap_method: 使用的截图方式 / screenshot method used
            mouse_method: 使用的鼠标输入方式 / mouse input method used
            keyboard_method: 使用的键盘输入方式 / keyboard input method used

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class MacOSController(Controller):
    """MacOS 控制器 / MacOS controller"""
    def __init__(self, window_id: int, screencap_method: int = ..., input_method: int = ...) -> None:
        """创建 MacOS 控制器 / Create MacOS controller

        Args:
            window_id: 窗口 ID / window ID
            screencap_method: 使用的截图方式 / screenshot method used
            input_method: 使用的输入方式 / input method used

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class AndroidNativeController(Controller):
    """Android Native 控制器 / Android native controller"""
    def __init__(self, config: dict[str, Any]) -> None:
        """创建 Android Native 控制器 / Create Android native controller

        Args:
            config: 控制器配置 JSON 对象 / controller config JSON object

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class PlayCoverController(Controller):
    """PlayCover 控制器 / PlayCover controller

    用于在 macOS 上控制通过 PlayCover 运行的 iOS 应用
    For controlling iOS apps running via PlayCover on macOS
    """
    def __init__(self, address: str, uuid: str) -> None:
        """创建 PlayCover 控制器 / Create PlayCover controller

        Args:
            address: PlayTools 服务地址 (host:port) / PlayTools service endpoint (host:port)
            uuid: 目标应用 bundle identifier / Target app bundle identifier

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class WlRootsController(Controller):
    """WlRoots 控制器 / WlRoots controller

    用于在 Linux 上控制在 wlroots 合成器中运行的应用
    For controlling apps running in wlroots compositor on Linux
    """
    def __init__(self, wlr_socket_path: str, use_win32_vk_code: bool = ...) -> None:
        """创建 WlRoots 控制器 / Create WlRoots controller

        Args:
            wlr_socket_path: Wayland Socket 路径 / Wayland Socket Path
            use_win32_vk_code: 为 True 时按键被视为 Win32 VK 键码并转换为 Linux evdev 码；
                默认 False，按原始 evdev 码处理
                / When True, key codes are interpreted as Win32 Virtual-Key codes and translated
                to Linux evdev codes internally; default False passes raw evdev codes through

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class DbgController(Controller):
    """调试控制器，轮播图片截图，基本输入操作直接返回成功

    Debug controller that cycles through images from a directory"""
    def __init__(self, read_path: Union[str, Path]) -> None:
        """创建调试控制器 / Create debug controller

        Args:
            read_path: 图片目录（或单个图片文件）路径。连接时加载所有图片，截图时轮播。

                        Path to a directory of images (or a single image file). Images are loaded on
                        connect and cycled on screencap.

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class ReplayController(Controller):
    """回放控制器，用于回放录制文件 / Replay controller for replaying recorded operations"""
    def __init__(self, recording_path: Union[str, Path]) -> None:
        """创建回放控制器 / Create replay controller

        Args:
            recording_path: 录制 JSONL 文件路径，由 RecordController 写入。截图路径基于该文件所在目录解析。

                            Path to the recording JSONL file written by RecordController. Screenshot
                            paths are resolved relative to this file's parent directory.

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class RecordController(Controller):
    """录制控制器，包装现有控制器并记录所有操作
    Record controller that wraps an existing controller and records all operations"""
    def __init__(self, inner: Controller, recording_path: Union[str, Path]) -> None:
        """创建录制控制器 / Create record controller

        Args:
            inner: 被包装的内部控制器 / The inner controller to wrap
            recording_path: 录制 JSONL 文件输出路径。截图会保存到同目录下的 "{stem}-Screenshot" 文件夹。

                            Path to the recording JSONL file to write. Screenshots are saved to a
                            "{stem}-Screenshot" folder in the same directory.

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class GamepadController(Controller):
    """虚拟手柄控制器 (仅 Windows) / Virtual gamepad controller (Windows only)

    通过 ViGEm 模拟 Xbox 360 或 DualShock 4 手柄，用于控制需要手柄输入的游戏。
    Emulates Xbox 360 or DualShock 4 gamepad via ViGEm for controlling games that require gamepad
    input.

    需要安装 ViGEm Bus Driver: https://github.com/ViGEm/ViGEmBus/releases
    Requires ViGEm Bus Driver: https://github.com/ViGEm/ViGEmBus/releases

    手柄操作映射:
    - click_key/key_down/key_up: 数字按键 (使用 MaaGamepadButtonEnum)
    - touch_down/touch_move/touch_up: 摇杆和扳机 (contact 使用 MaaGamepadContactEnum)
      - contact 0: 左摇杆 (x, y: -32768~32767)
      - contact 1: 右摇杆 (x, y: -32768~32767)
      - contact 2: 左扳机 (pressure: 0~255)
      - contact 3: 右扳机 (pressure: 0~255)
    """
    def __init__(self, hWnd: Union[ctypes.c_void_p, int, None], gamepad_type: int = ..., screencap_method: int = ...) -> None:
        """创建虚拟手柄控制器 / Create virtual gamepad controller

        Args:
            hWnd: 窗口句柄，用于截图 (可为 None，不需要截图时)
            Window handle for screencap (can be None if screencap not needed)
            gamepad_type: 手柄类型 (MaaGamepadTypeEnum.Xbox360 或 MaaGamepadTypeEnum.DualShock4)
            Gamepad type
            screencap_method: 截图方式 (当 hWnd 不为 None 时使用)
            Screencap method (used when hWnd is not None)

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    


class CustomController(Controller):
    _callbacks: MaaCustomControllerCallbacks
    def __init__(self) -> None:
        ...
    
    @property
    def c_handle(self) -> Any:
        ...
    
    @property
    def c_arg(self) -> ctypes.c_void_p:
        ...
    
    @abstractmethod
    def connect(self) -> bool:
        ...
    
    def connected(self) -> bool:
        """检查是否已连接（可选实现，默认返回 True）"""
        ...
    
    @abstractmethod
    def request_uuid(self) -> str:
        ...
    
    def get_features(self) -> int:
        ...
    
    @abstractmethod
    def start_app(self, intent: str) -> bool:
        ...
    
    @abstractmethod
    def stop_app(self, intent: str) -> bool:
        ...
    
    @abstractmethod
    def screencap(self) -> numpy.ndarray:
        ...
    
    @abstractmethod
    def click(self, x: int, y: int) -> bool:
        ...
    
    @abstractmethod
    def swipe(self, x1: int, y1: int, x2: int, y2: int, duration: int) -> bool:
        ...
    
    @abstractmethod
    def touch_down(self, contact: int, x: int, y: int, pressure: int) -> bool:
        ...
    
    @abstractmethod
    def touch_move(self, contact: int, x: int, y: int, pressure: int) -> bool:
        ...
    
    @abstractmethod
    def touch_up(self, contact: int) -> bool:
        ...
    
    @abstractmethod
    def click_key(self, keycode: int) -> bool:
        ...
    
    @abstractmethod
    def input_text(self, text: str) -> bool:
        ...
    
    @abstractmethod
    def key_down(self, keycode: int) -> bool:
        ...
    
    @abstractmethod
    def key_up(self, keycode: int) -> bool:
        ...
    
    def scroll(self, dx: int, dy: int) -> bool:
        ...
    
    def relative_move(self, dx: int, dy: int) -> bool:
        ...
    
    def shell(self, cmd: str, timeout: int) -> Optional[str]:
        ...
    
    def inactive(self) -> bool:
        """设置控制器为不活跃状态（可选实现，默认返回 True）"""
        ...
    
    def get_custom_info(self) -> dict[str, Any]:
        """获取自定义控制器的额外信息（可选实现，默认返回空字典）

        Get custom controller's extra info (optional, returns empty dict by default)

        Returns:
            Dict[str, Any]: 额外信息，将与基础信息合并 / Extra info, will be merged with base info
        """
        ...
    


class ControllerEventSink(EventSink):
    @dataclass
    class ControllerActionDetail:
        ctrl_id: int
        uuid: str
        action: str
        param: dict[str, Any]
        info: dict[str, Any]
        ...
    
    
    def on_controller_action(self, controller: Controller, noti_type: NotificationType, detail: ControllerActionDetail): # -> None:
        ...
    
    def on_raw_notification(self, controller: Controller, msg: str, details: dict[str, Any]) -> None:
        ...
    


