"""
This type stub file was generated by pyright.
"""

import ctypes
from enum import IntEnum
from typing import Any

class NotificationType(IntEnum):
    """通知类型枚举 / Notification type enumeration

    用于标识事件回调的状态类型。
    Used to identify the status type of event callbacks.

    Attributes:
        Unknown: 未知类型 / Unknown type
        Starting: 开始 / Starting
        Succeeded: 成功 / Succeeded
        Failed: 失败 / Failed
    """
    Unknown = ...
    Starting = ...
    Succeeded = ...
    Failed = ...


class EventSink:
    """事件监听器基类 / Event sink base class

    用于接收 MaaFramework 各种事件回调的基类。
    派生类包括 ResourceEventSink、ControllerEventSink、TaskerEventSink、ContextEventSink。
    Base class for receiving various event callbacks from MaaFramework.
    Derived classes include ResourceEventSink, ControllerEventSink, TaskerEventSink,
    ContextEventSink.
    """
    def on_unknown_notification(self, instance: Any, msg: str, details: dict[str, Any]) -> None:
        """处理未知类型的通知 / Handle unknown notification

        当收到无法识别的通知时调用。
        Called when an unrecognized notification is received.

        Args:
            instance: 相关实例对象 / Related instance object
            msg: 消息类型 / Message type
            details: 消息详情 / Message details
        """
        ...
    
    @property
    def c_callback(self) -> Any:
        ...
    
    @property
    def c_callback_arg(self) -> ctypes.c_void_p:
        ...
    


