"""
This type stub file was generated by pyright.
"""

import ctypes
import pathlib
from typing import Optional
from .define import *

class Library:
    """库加载管理器 / Library loading manager

    管理 MaaFramework 各动态库的加载和访问。
    Manages loading and access to MaaFramework dynamic libraries.
    """
    _is_agent_server: bool = ...
    _framework: Optional[ctypes.CDLL] = ...
    _toolkit: Optional[ctypes.CDLL] = ...
    _agent_client: Optional[ctypes.CDLL] = ...
    _agent_server: Optional[ctypes.CDLL] = ...
    _lib_type: Optional[type[ctypes.CDLL]] = ...
    framework_libpath: Optional[pathlib.Path] = ...
    toolkit_libpath: Optional[pathlib.Path] = ...
    agent_client_libpath: Optional[pathlib.Path] = ...
    agent_server_libpath: Optional[pathlib.Path] = ...
    @classmethod
    def open(cls, path: pathlib.Path, agent_server: bool = ...) -> None:
        """打开并加载库 / Open and load libraries

        Args:
            path: 库文件所在目录 / Directory containing library files
            agent_server: 是否以 AgentServer 模式加载 / Whether to load in AgentServer mode

        Raises:
            FileNotFoundError: 如果路径不存在
        """
        ...
    
    @classmethod
    def framework(cls) -> ctypes.CDLL:
        """获取 MaaFramework 库 / Get MaaFramework library

        Returns:
            (ctypes.CDLL | ctypes.WinDLL): MaaFramework 动态库对象 / MaaFramework dynamic library object
        """
        ...
    
    @classmethod
    def toolkit(cls) -> ctypes.CDLL:
        """获取 MaaToolkit 库 / Get MaaToolkit library

        Returns:
            (ctypes.CDLL | ctypes.WinDLL): MaaToolkit 动态库对象 / MaaToolkit dynamic library object

        Raises:
            ValueError: 如果在 AgentServer 模式下调用
        """
        ...
    
    @classmethod
    def agent_client(cls) -> ctypes.CDLL:
        """获取 MaaAgentClient 库 / Get MaaAgentClient library

        Returns:
            (ctypes.CDLL | ctypes.WinDLL): MaaFramework 动态库对象 / MaaFramework dynamic library object

        Raises:
            ValueError: 如果在 AgentServer 模式下调用
        """
        ...
    
    @classmethod
    def agent_server(cls) -> ctypes.CDLL:
        """获取 MaaAgentServer 库 / Get MaaAgentServer library

        Returns:
            (ctypes.CDLL | ctypes.WinDLL): MaaAgentServer 动态库对象
            MaaAgentServer dynamic library object

        Raises:
            ValueError: 如果不在 AgentServer 模式下调用
        """
        ...
    
    @classmethod
    def is_agent_server(cls) -> bool:
        """判断是否为 AgentServer 模式 / Check if in AgentServer mode

        Returns:
            bool: 是否为 AgentServer 模式 / Whether in AgentServer mode
        """
        ...
    
    @classmethod
    def version(cls) -> str:
        """获取 MaaFramework 版本 / Get MaaFramework version

        Returns:
            str: 版本字符串 / Version string
        """
        ...
    
    _api_properties_initialized: bool = ...


