"""
This type stub file was generated by pyright.
"""

import pathlib
import numpy
from dataclasses import dataclass
from typing import Any, Callable, Optional, TYPE_CHECKING, Union
from .define import *
from .event_sink import EventSink, NotificationType
from .job import Job
from .pipeline import JActionParam, JActionType, JPipelineData, JRecognitionParam, JRecognitionType
from .custom_action import CustomAction
from .custom_recognition import CustomRecognition

if TYPE_CHECKING:
    ...
class Resource:
    _handle: MaaResourceHandle
    _own: bool
    def __init__(self, handle: Optional[MaaResourceHandle] = ...) -> None:
        """创建资源 / Create resource

        Args:
            handle: 可选的外部句柄 / Optional external handle

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    
    def __del__(self): # -> None:
        ...
    
    def post_bundle(self, path: Union[pathlib.Path, str]) -> Job:
        """异步加载资源 / Asynchronously load resources from path

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        Args:
            path: 资源路径 / Resource path

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def post_ocr_model(self, path: Union[pathlib.Path, str]) -> Job:
        """异步加载 OCR 模型 / Asynchronously load OCR model from path

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        Args:
            path: OCR 模型目录路径 / OCR model directory path

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def post_pipeline(self, path: Union[pathlib.Path, str]) -> Job:
        """异步加载 Pipeline / Asynchronously load pipeline from path

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        支持加载目录或单个 json/jsonc 文件
        Supports loading a directory or a single json/jsonc file

        Args:
            path: Pipeline 目录或文件路径 / Pipeline directory or file path

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def post_image(self, path: Union[pathlib.Path, str]) -> Job:
        """异步加载图片资源 / Asynchronously load image resources from path

        这是一个异步操作，会立即返回一个 Job 对象
        This is an asynchronous operation that immediately returns a Job object

        支持加载目录或单个图片文件
        Supports loading a directory or a single image file

        Args:
            path: 图片目录或文件路径 / Image directory or file path

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    def override_pipeline(self, pipeline_override: dict[str, Any]) -> bool:
        """覆盖 pipeline / Override pipeline_override

        Args:
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def override_next(self, name: str, next_list: list[str]) -> bool:
        """覆盖任务的 next 列表 / Override the next list of task

        注意：此方法会直接设置 next 列表，即使节点不存在也会创建
        Note: This method directly sets the next list, creating the node if it doesn't exist

        Args:
            name: 任务名 / Task name
            next_list: next 列表 / Next list

        Returns:
            bool: 总是返回 True / Always returns True
        """
        ...
    
    def override_image(self, image_name: str, image: numpy.ndarray) -> bool:
        """覆盖图片 / Override the image corresponding to image_name

        Args:
            image_name: 图片名 / Image name
            image: 图片数据 / Image data

        Returns:
            bool: 总是返回 True / Always returns True
        """
        ...
    
    def get_node_data(self, name: str) -> Optional[dict[str, Any]]:
        """获取任务当前的定义 / Get the current definition of task

        Args:
            name: 任务名 / Task name

        Returns:
            Optional[Dict]: 任务定义字典，如果不存在则返回 None / Task definition dict, or None if not exists
        """
        ...
    
    def get_node_object(self, name: str) -> Optional[JPipelineData]:
        """获取任务当前的定义（解析为对象） / Get the current definition of task (parsed as object)

        Args:
            name: 任务名 / Task name

        Returns:
            Optional[JPipelineData]: 任务定义对象，如果不存在则返回 None
            Task definition object, or None if not exists
        """
        ...
    
    def get_default_recognition_param(self, reco_type: JRecognitionType) -> Optional[JRecognitionParam]:
        """获取指定识别类型的默认参数 / Get default parameters for specified recognition type

        Args:
            reco_type: 识别类型 / Recognition type

        Returns:
            Optional[JRecognitionParam]: 默认参数对象，如果不存在则返回 None
            Default parameter object, or None if not exists
        """
        ...
    
    def get_default_action_param(self, action_type: JActionType) -> Optional[JActionParam]:
        """获取指定动作类型的默认参数 / Get default parameters for specified action type

        Args:
            action_type: 动作类型 / Action type

        Returns:
            Optional[JActionParam]: 默认参数对象，如果不存在则返回 None
            Default parameter object, or None if not exists
        """
        ...
    
    @property
    def loaded(self) -> bool:
        """判断是否加载正常 / Check if resources loaded normally

        Returns:
            bool: 是否已加载 / Whether loaded
        """
        ...
    
    def clear(self) -> bool:
        """清除已加载内容 / Clear loaded content

        如果资源正在加载中，此方法会失败
        This method will fail if resources are currently loading

        Returns:
            bool: 成功返回 True，如果正在加载中则返回 False / Returns True on success, False if currently loading
        """
        ...
    
    def use_cpu(self) -> bool:
        """使用 CPU 进行推理 / Use CPU for inference

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def use_directml(self, device_id: int = ...) -> bool:
        """使用 DirectML 进行推理 / Use DirectML for inference

        Args:
            device_id: 设备 id，默认为自动选择 / Device id, default is Auto

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def use_coreml(self, coreml_flag: int = ...) -> bool:
        """使用 CoreML 进行推理 / Use CoreML for inference

        Args:
            coreml_flag: CoreML 标志，默认为自动选择 / CoreML flag, default is Auto

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def use_auto_ep(self) -> bool:
        """自动选择推理执行提供者 / Auto select inference execution provider

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def set_gpu(self, gpu_id: int) -> bool:
        """
        Deprecated, please use `use_directml`, `use_coreml` or `use_cuda` instead.
        """
        ...
    
    def set_cpu(self) -> bool:
        """
        Deprecated, please use `use_cpu` instead.
        """
        ...
    
    def set_auto_device(self) -> bool:
        """
        Deprecated, please use `use_auto_ep` instead.
        """
        ...
    
    def custom_recognition(self, name: str) -> Callable[[type[CustomRecognition]], type[CustomRecognition]]:
        """自定义识别器装饰器 / Custom recognition decorator

        Args:
            name: 识别器名称，需与 Pipeline 中的 custom_recognition 字段匹配
            Recognition name, should match the custom_recognition field in Pipeline

        Returns:
            装饰器函数 / Decorator function
        """
        ...
    
    def register_custom_recognition(self, name: str, recognition: CustomRecognition) -> bool:
        """注册自定义识别器 / Register a custom recognizer

        Args:
            name: 名称 / Name
            recognition: 自定义识别器 / Custom recognizer

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def unregister_custom_recognition(self, name: str) -> bool:
        """移除自定义识别器 / Remove the custom recognizer

        Args:
            name: 名称 / Name

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def clear_custom_recognition(self) -> bool:
        """移除所有自定义识别器 / Remove all custom recognizers

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def custom_action(self, name: str) -> Callable[[type[CustomAction]], type[CustomAction]]:
        """自定义动作装饰器 / Custom action decorator

        Args:
            name: 动作名称，需与 Pipeline 中的 custom_action 字段匹配
            Action name, should match the custom_action field in Pipeline

        Returns:
            装饰器函数 / Decorator function
        """
        ...
    
    def register_custom_action(self, name: str, action: CustomAction) -> bool:
        """注册自定义操作 / Register a custom action

        Args:
            name: 名称 / Name
            action: 自定义操作 / Custom action

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def unregister_custom_action(self, name: str) -> bool:
        """移除自定义操作 / Remove the custom action

        Args:
            name: 名称 / Name

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def clear_custom_action(self) -> bool:
        """移除所有自定义操作 / Remove all custom actions

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def node_list(self) -> list[str]:
        """获取任务列表 / Get task list

        Returns:
            list[str]: 任务名列表 / List of task names

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def custom_recognition_list(self) -> list[str]:
        """获取已注册的自定义识别器列表 / Get registered custom recognizer list

        Returns:
            list[str]: 自定义识别器名列表 / List of custom recognizer names

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def custom_action_list(self) -> list[str]:
        """获取已注册的自定义操作列表 / Get registered custom action list

        Returns:
            list[str]: 自定义操作名列表 / List of custom action names

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def hash(self) -> str:
        """获取资源 hash / Get resource hash

        Returns:
            str: 资源 hash / Resource hash

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    _sink_holder: dict[int, ResourceEventSink] = ...
    def add_sink(self, sink: ResourceEventSink) -> Optional[int]:
        """添加资源事件监听器 / Add resource event listener

        Args:
            sink: 事件监听器 / Event sink

        Returns:
            Optional[int]: 监听器 id，失败返回 None / Listener id, or None if failed
        """
        ...
    
    def remove_sink(self, sink_id: int) -> None:
        """移除资源事件监听器 / Remove resource event listener

        Args:
            sink_id: 监听器 id / Listener id
        """
        ...
    
    def clear_sinks(self) -> None:
        """清除所有资源事件监听器 / Clear all resource event listeners"""
        ...
    
    def set_inference(self, execution_provider: int, device_id: int) -> bool:
        ...
    
    _api_properties_initialized: bool = ...


class ResourceEventSink(EventSink):
    @dataclass
    class ResourceLoadingDetail:
        res_id: int
        path: str
        type: str
        hash: str
        ...
    
    
    def on_resource_loading(self, resource: Resource, noti_type: NotificationType, detail: ResourceLoadingDetail): # -> None:
        ...
    
    def on_raw_notification(self, resource: Resource, msg: str, details: dict[str, Any]) -> None:
        ...
    


