"""
This type stub file was generated by pyright.
"""

import numpy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, TYPE_CHECKING, Union
from .controller import Controller
from .define import *
from .event_sink import EventSink, NotificationType
from .job import Job, TaskJob
from .pipeline import JActionParam, JActionType, JRecognitionParam, JRecognitionType
from .resource import Resource
from .context import ContextEventSink

if TYPE_CHECKING:
    ...
class Tasker:
    _handle: MaaTaskerHandle
    _own: bool
    def __init__(self, handle: Optional[MaaTaskerHandle] = ...) -> None:
        """创建实例 / Create instance

        Args:
            handle: 可选的外部句柄 / Optional external handle

        Raises:
            RuntimeError: 如果创建失败
        """
        ...
    
    def __del__(self): # -> None:
        ...
    
    def bind(self, resource: Resource, controller: Controller) -> bool:
        """关联资源和控制器 / Bind resource and controller

        Args:
            resource: 资源对象 / Resource object
            controller: 控制器对象 / Controller object

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @property
    def resource(self) -> Resource:
        """获取关联的资源 / Get bound resource

        Returns:
            Resource: 资源对象 / Resource object

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def controller(self) -> Controller:
        """获取关联的控制器 / Get bound controller

        Returns:
            Controller: 控制器对象 / Controller object

        Raises:
            RuntimeError: 如果获取失败
        """
        ...
    
    @property
    def inited(self) -> bool:
        """判断是否正确初始化 / Check if initialized correctly

        Returns:
            bool: 是否已正确初始化 / Whether correctly initialized
        """
        ...
    
    def post_task(self, entry: str, pipeline_override: Optional[dict[str, Any]] = ...) -> TaskJob:
        """异步执行任务 / Asynchronously execute task

        这是一个异步操作，会立即返回一个 TaskJob 对象
        This is an asynchronous operation that immediately returns a TaskJob object

        Args:
            entry: 任务入口 / Task entry
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            TaskJob: 任务作业对象，可通过 status/wait 查询状态，通过 get() 获取结果，通过 override_pipeline() 动态修改
            pipeline

                Task job object, can query status via status/wait, get result via get(), modify
                pipeline via override_pipeline()
        """
        ...
    
    def post_recognition(self, reco_type: JRecognitionType, reco_param: JRecognitionParam, image: numpy.ndarray) -> TaskJob:
        """异步执行识别 / Asynchronously execute recognition

        Args:
            reco_type: 识别类型 / Recognition type
            reco_param: 识别参数 / Recognition parameters
            image: 前序截图 / Previous screenshot

        Returns:
            TaskJob: 任务作业对象 / Task job object
        """
        ...
    
    def post_action(self, action_type: JActionType, action_param: JActionParam, box: RectType = ..., reco_detail: str = ...) -> TaskJob:
        """异步执行操作 / Asynchronously execute action

        Args:
            action_type: 操作类型 / Action type
            action_param: 操作参数 / Action parameters
            box: 前序识别位置 / Previous recognition position
            reco_detail: 前序识别详情 / Previous recognition details

        Returns:
            TaskJob: 任务作业对象 / Task job object
        """
        ...
    
    @property
    def running(self) -> bool:
        """判断实例是否还在运行 / Check if instance is still running

        Returns:
            bool: 是否正在运行 / Whether running
        """
        ...
    
    def post_stop(self) -> Job:
        """异步停止实例 / Asynchronously stop instance

        这是一个异步操作，会立即返回一个 Job 对象
        停止操作会中断当前运行的任务，并停止资源加载和控制器操作
        This is an asynchronous operation that immediately returns a Job object
        The stop operation will interrupt the currently running task and stop resource loading and
        controller operations

        Returns:
            Job: 作业对象，可通过 status/wait 查询状态 / Job object, can query status via status/wait
        """
        ...
    
    @property
    def stopping(self) -> bool:
        """判断实例是否正在停止中(尚未停止) / Check if instance is stopping (not yet stopped)

        Returns:
            bool: 是否正在停止 / Whether stopping
        """
        ...
    
    def get_latest_node(self, name: str) -> Optional[NodeDetail]:
        """获取任务的最新节点号 / Get latest node id for task

        Args:
            name: 任务名 / Task name

        Returns:
            Optional[NodeDetail]: 节点详情，如果不存在则返回 None / Node detail, or None if not exists
        """
        ...
    
    def clear_cache(self) -> bool:
        """清理所有可查询的信息 / Clear all queryable information

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    def override_pipeline(self, task_id: int, pipeline_override: dict[str, Any]) -> bool:
        """覆盖指定任务的 pipeline / Override pipeline for specified task

        在任务执行期间动态修改 pipeline 配置
        Dynamically modify pipeline configuration during task execution

        Args:
            task_id: 任务 ID / Task ID
            pipeline_override: 用于覆盖的 json / JSON for overriding

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _sink_holder: dict[int, EventSink] = ...
    def add_sink(self, sink: TaskerEventSink) -> Optional[int]:
        """添加实例事件监听器 / Add instance event listener

        Args:
            sink: 事件监听器 / Event sink

        Returns:
            Optional[int]: 监听器 id，失败返回 None / Listener id, or None if failed
        """
        ...
    
    def remove_sink(self, sink_id: int) -> None:
        """移除实例事件监听器 / Remove instance event listener

        Args:
            sink_id: 监听器 id / Listener id
        """
        ...
    
    def clear_sinks(self) -> None:
        """清除所有实例事件监听器 / Clear all instance event listeners"""
        ...
    
    def add_context_sink(self, sink: ContextEventSink) -> Optional[int]:
        """添加上下文事件监听器 / Add context event listener

        Args:
            sink: 上下文事件监听器 / Context event sink

        Returns:
            Optional[int]: 监听器 id，失败返回 None / Listener id, or None if failed
        """
        ...
    
    def remove_context_sink(self, sink_id: int) -> None:
        """移除上下文事件监听器 / Remove context event listener

        Args:
            sink_id: 监听器 id / Listener id
        """
        ...
    
    def clear_context_sinks(self) -> None:
        """清除所有上下文事件监听器 / Clear all context event listeners"""
        ...
    
    def get_recognition_detail(self, reco_id: int) -> Optional[RecognitionDetail]:
        """获取识别信息 / Get recognition info

        Args:
            reco_id: 识别号 / Recognition id

        Returns:
            Optional[RecognitionDetail]: 识别详情，如果不存在则返回 None
            Recognition detail, or None if not exists
        """
        ...
    
    def get_action_detail(self, action_id: int) -> Optional[ActionDetail]:
        """获取操作信息 / Get action info

        Args:
            action_id: 操作号 / Action id

        Returns:
            Optional[ActionDetail]: 操作详情，如果不存在则返回 None / Action detail, or None if not exists
        """
        ...
    
    def get_wait_freezes_detail(self, wf_id: int) -> Optional[WaitFreezesDetail]:
        """获取等待画面静止信息 / Get wait freezes info

        Args:
            wf_id: Wait Freezes ID

        Returns:
            Optional[WaitFreezesDetail]: 等待画面静止详情 / Wait freezes detail, or None if not exists
        """
        ...
    
    def get_node_detail(self, node_id: int) -> Optional[NodeDetail]:
        """获取节点信息 / Get node info

        Args:
            node_id: 节点号 / Node id

        Returns:
            Optional[NodeDetail]: 节点详情，如果不存在则返回 None / Node detail, or None if not exists
        """
        ...
    
    def get_task_detail(self, task_id: int) -> Optional[TaskDetail]:
        """获取任务信息 / Get task info

        Args:
            task_id: 任务号 / Task id

        Returns:
            Optional[TaskDetail]: 任务详情，如果不存在则返回 None / Task detail, or None if not exists
        """
        ...
    
    @staticmethod
    def set_log_dir(path: Union[Path, str]) -> bool:
        """设置日志路径 / Set the log path

        Args:
            path: 日志路径 / Log path

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_save_draw(save_draw: bool) -> bool:
        """设置是否将识别保存到日志路径/vision中 / Set whether to save recognition results to log path/vision

        开启后 RecoDetail 将可以获取到 draws / When enabled, RecoDetail can retrieve draws

        Args:
            save_draw: 是否保存 / Whether to save

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_recording(recording: bool) -> bool:
        """
        Deprecated
        """
        ...
    
    @staticmethod
    def set_stdout_level(level: LoggingLevelEnum) -> bool:
        """设置日志输出到 stdout 中的级别 / Set the log output level to stdout

        Args:
            level: 日志级别 / Logging level

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_debug_mode(debug_mode: bool) -> bool:
        """设置是否启用调试模式 / Set whether to enable debug mode

        调试模式下, RecoDetail 将可以获取到 raw/draws; 所有任务都会被视为 focus 而产生回调
        In debug mode, RecoDetail can retrieve raw/draws; all tasks are treated as focus and produce
        callbacks

        Args:
            debug_mode: 是否启用调试模式 / Whether to enable debug mode

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_save_on_error(save_on_error: bool) -> bool:
        """设置是否在错误时保存截图到日志路径/on_error中
        Set whether to save screenshot on error to log path/on_error

        Args:
            save_on_error: 是否保存 / Whether to save

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_draw_quality(quality: int) -> bool:
        """设置识别可视化图像的 JPEG 质量 / Set the JPEG quality for recognition visualization images

        Args:
            quality: JPEG 质量（0-100），默认 85 / JPEG quality (0-100), default 85

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def set_reco_image_cache_limit(limit: int) -> bool:
        """设置识别图像缓存数量限制 / Set the recognition image cache limit

        Args:
            limit: 缓存数量限制，默认 4096 / Cache limit, default 4096

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def load_plugin(path: Union[Path, str]) -> bool:
        """加载插件 / Load plugin

        可以使用完整路径或仅使用名称, 仅使用名称时会在系统目录和当前目录中搜索. 也可以递归搜索目录中的插件
        Can use full path or name only. When using name only, will search in system directory and
        current directory. Can also recursively search for plugins in a directory

        Args:
            path: 插件库路径或名称 / Plugin library path or name

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    _api_properties_initialized: bool = ...


class TaskerEventSink(EventSink):
    @dataclass
    class TaskerTaskDetail:
        task_id: int
        entry: str
        uuid: str
        hash: str
        ...
    
    
    def on_tasker_task(self, tasker: Tasker, noti_type: NotificationType, detail: TaskerTaskDetail) -> None:
        ...
    
    def on_raw_notification(self, tasker: Tasker, msg: str, details: dict[str, Any]) -> None:
        ...
    


