"""
This type stub file was generated by pyright.
"""

import ctypes
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union
from .define import *

@dataclass
class AdbDevice:
    """ADB 设备信息 / ADB device information

    通过 Toolkit.find_adb_devices 获取。
    Obtained via Toolkit.find_adb_devices.

    Attributes:
        name: 设备名称 / Device name
        adb_path: adb 可执行文件路径 / Path to adb executable
        address: 设备地址 (如 127.0.0.1:5555) / Device address (e.g., 127.0.0.1:5555)
        screencap_methods: 可用的截图方式位掩码 / Available screenshot methods bitmask
        input_methods: 可用的输入方式位掩码 / Available input methods bitmask
        config: 额外配置信息 / Extra configuration
    """
    name: str
    adb_path: Path
    address: str
    screencap_methods: int
    input_methods: int
    config: dict[str, Any]
    ...


@dataclass
class DesktopWindow:
    """桌面窗口信息 / Desktop window information

    通过 Toolkit.find_desktop_windows 获取。
    Obtained via Toolkit.find_desktop_windows.

    Attributes:
        hwnd: 窗口句柄 / Window handle
        class_name: 窗口类名 / Window class name
        window_name: 窗口标题 / Window title
    """
    hwnd: ctypes.c_void_p
    class_name: str
    window_name: str
    ...


class Toolkit:
    """工具包 / Toolkit

    提供设备发现、配置初始化等辅助功能。
    Provides auxiliary functions such as device discovery and configuration initialization.
    """
    @staticmethod
    def init_option(user_path: Union[str, Path], default_config: Optional[dict[str, Any]] = ...) -> bool:
        """从 user_path 中加载全局配置 / Load global config from user_path

        Args:
            user_path: 配置存储路径 / Config storage path
            default_config: 默认配置 / Default config

        Returns:
            bool: 是否成功 / Whether successful
        """
        ...
    
    @staticmethod
    def find_adb_devices(specified_adb: Optional[Union[str, Path]] = ...) -> list[AdbDevice]:
        """搜索所有已知安卓模拟器 / Search all known Android emulators

        Args:
            specified_adb: 可选，指定 adb 路径进行搜索 / Optional, search using specified adb path

        Returns:
            List[AdbDevice]: 设备列表 / Device list
        """
        ...
    
    @staticmethod
    def find_desktop_windows() -> list[DesktopWindow]:
        """查询所有窗口信息 / Query all window info

        Returns:
            List[DesktopWindow]: 窗口列表 / Window list
        """
        ...
    
    @staticmethod
    def macos_check_permission(perm: MaaMacOSPermissionEnum) -> bool:
        """检查 macOS 权限 / Check macOS permission

        检查应用是否已获得指定的 macOS 系统权限。
        Check if the application has been granted the specified macOS system permission.

        Args:
            perm: 权限类型 / Permission type

        Returns:
            bool: 是否已授权 / Whether permission is granted
        """
        ...
    
    @staticmethod
    def macos_request_permission(perm: MaaMacOSPermissionEnum) -> bool:
        """请求 macOS 权限 / Request macOS permission

        向用户请求指定的 macOS 系统权限。系统可能会弹出授权对话框。
        Request the specified macOS system permission from user. System may show an authorization
        dialog.

        Args:
            perm: 权限类型 / Permission type

        Returns:
            bool: 是否成功请求（不代表已授权）/ Whether request succeeded (doesn't mean granted)
        """
        ...
    
    @staticmethod
    def macos_reveal_permission_settings(perm: MaaMacOSPermissionEnum) -> bool:
        """打开 macOS 权限设置 / Open macOS permission settings

        打开系统偏好设置中对应权限的设置页面。
        Open the corresponding permission settings page in System Preferences.

        Args:
            perm: 权限类型 / Permission type

        Returns:
            bool: 是否成功打开 / Whether successfully opened
        """
        ...
    
    _api_properties_initialized: bool = ...


